POST /register HTTP/1.1
Host: localhost:3000
Content-Length: 614
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name=""fname""

dman
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name=""lname""

cryus
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name=""email""

iluazazav@gmail.com
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name=""password""

@Remigio99
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="/C:/Users/damie/Downloads/pictures here/hehe.jpg"
Content-Type: image/jpeg

(data)
------WebKitFormBoundary7MA4YWxkTrZu0gW--






###
POST http://localhost:3000/register HTTP/1.1
content-type: application/json

{
        "fname":"Damien",
        "lname":"Cruz",
        "email":"Damien@bal.email",
        "password":"P@ssw0rd123!"
}

###
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
        "email":"Damien@bal.email",
        "password":"P@ssw0rd123!"
}

###
POST http://localhost:3000/creategig HTTP/1.1
Content-Type: application/json

{
  "jobname": "new gig",
  "pay": 700,
  "categories": "Design",
  "description": "UX developer to help with a design for a website for my new restaurant",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRjODBkMGZhODE5ZDJjNTkxYjBiMDU2IiwiaWF0IjoxNjkwODQ0NDk0LCJleHAiOjE2OTA4NTE2OTR9.n2TUWLfilpS8F_5XwEYSLgDrdneBzfp9GDaYXIzBPrI",
  "timestamp": "2023-07-31T12:34:56.789Z"
}


###
POST http://localhost:3000/modifygig HTTP/1.1
content-type: application/json

{
        "_id": "64bade53cc9ad044a5253a0f",
        "jobname": "Engineer Developer Needed",
        "pay": 700,
        "categories": "Design",
        "description": "UX devolper to help with a design for a website for my new resturaunt"
}

###
POST /welcome HTTP/1.1
Host: localhost:3000
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiNzE3ZDIzYWJiYzkxNjMyZjU0Mjk3IiwiaWF0IjoxNjg5NzIxNzY3LCJleHAiOjE2ODk3MjE4Mjd9.vO-4EqpilSnG_EkZoCHj5MZsyQ7hVTf7zPOtr1L9xlA
Content-Type: application/json
Content-Length: 192

{"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiNzE3ZDIzYWJiYzkxNjMyZjU0Mjk3IiwiaWF0IjoxNjg5NzIxNzY3LCJleHAiOjE2ODk3MjE4Mjd9.vO-4EqpilSnG_EkZoCHj5MZsyQ7hVTf7zPOtr1L9xlA"
}


###
DELETE http://localhost:3000/deletegig HTTP/1.1
content-type: application/json

{
        "_id": "64c83eeaa821c73851266c95"
}

###

GET http://localhost:3000/readgig/64c83eeaa821c73851266c95 HTTP/1.1 HTTP/1.1

###
GET http://localhost:3000/usersByName/damien HTTP/1.1 HTTP/1.1

###
GET http://localhost:3000/gigsLookUp/h HTTP/1.1 HTTP/1.1

###
GET http://localhost:3000/jobsByFilter/Web designer/Seattle/Full Time/1000/10000 HTTP/1.1 HTTP/1.1

###
POST http://localhost:3000/modifyprofile HTTP/1.1
content-type: application/json

{
        "_id":"64c811426b0ee3585219f253",
        "lname":"Cruz"
}