###
POST http://localhost:3000/register HTTP/1.1
content-type: application/json

{
        "fname":"Damien",
        "lname":"Cruz",
        "email":"Damien@bal.email",
        "password":"P@ssw0rd123!"
}

###
POST http://localhost:3000/modifygig HTTP/1.1
content-type: application/json

{
        "_id": "64b5acf2e629c7caa66e3eec",
        "jobname": "engineer Developer Needed",
        "pay": 700,
        "categories": "Design",
        "description": "UX devolper to help with a design for a website for my new resturaunt"
}